version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.0
    steps:
      - checkout
      - run:
          name: Install and run linter on go files
          command: make tools && make linter
      - run:
        name: run unit tests
        command: make test
