version: 2
  jobs:
    build:
      docker:
        - image: circleci/goland:1.13
        - image: circleci/mysql:8.0.17
          environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: secret1234
            MYSQL_DATABASE: db_test
            MYSQL_USER: foundation
            MYSQL_PASSWORD: secret1234
            LANG: C.UTF-8
          entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
          security_opt:
            - seccomp:unconfined
      steps:
        - checkout
        - run: make test